/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

//import java.util.logging.Level;

import Domain.Admin;
import Domain.ObjectClass;
import Service.Service;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JScrollBar;

//import java.util.logging.Logger;
//import javax.swing.UIManager;
//import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author paulh
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login(Service serviceAdmin,Service serviceClient,Service serviceEmployee) {
        this.serviceAdmin=serviceAdmin;
        this.serviceClient=serviceClient;
        this.serviceEmployee=serviceEmployee;
        initComponents();
        panelClient.setVisible(false);// important pt tabel



        //transparentLogin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogIn = new javax.swing.JPanel();
        signUpLabel = new javax.swing.JLabel();
        logInLabel = new javax.swing.JLabel();
        logInSeparator = new javax.swing.JSeparator();
        signUpSeparator = new javax.swing.JSeparator();
        logInPanel = new javax.swing.JPanel();
        passwordLogInField = new javax.swing.JPasswordField();
        icon2LogInLabel = new javax.swing.JLabel();
        usernameLogInSeparator = new javax.swing.JSeparator();
        passwordLogInSeparator = new javax.swing.JSeparator();
        usernameLogInField = new javax.swing.JTextField();
        icon1LogInLabel = new javax.swing.JLabel();
        icon4LogInLabel = new javax.swing.JLabel();
        icon3LogInLabel = new javax.swing.JLabel();
        checkLogInLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        passwordSignUpField = new javax.swing.JPasswordField();
        icon2SignUpLabel = new javax.swing.JLabel();
        usenameSignUpSeparator = new javax.swing.JSeparator();
        passwordSignUpSeparator = new javax.swing.JSeparator();
        usernameSignUpField = new javax.swing.JTextField();
        icon1SignUpLabel = new javax.swing.JLabel();
        icon8SignUpLabel = new javax.swing.JLabel();
        icon7SignUpLabel = new javax.swing.JLabel();
        icon3SignUpLabel = new javax.swing.JLabel();
        firstNameSignUpField = new javax.swing.JTextField();
        nameSignUpSeparator = new javax.swing.JSeparator();
        lastNameSignUpField = new javax.swing.JTextField();
        icon4SignUpLabel = new javax.swing.JLabel();
        eMailSignUpSeparator = new javax.swing.JSeparator();
        eMailSignUpField = new javax.swing.JTextField();
        icon5SignUpLabel = new javax.swing.JLabel();
        occupationSignUpSeparator = new javax.swing.JSeparator();
        clientSignUpLabel = new javax.swing.JLabel();
        employeeSignUpLabel = new javax.swing.JLabel();
        adminSignUpLabel = new javax.swing.JLabel();
        cnpSignUpField = new javax.swing.JTextField();
        icon6SignUpLabel = new javax.swing.JLabel();
        numbersSignUpSeparator = new javax.swing.JSeparator();
        phoneSignUpField = new javax.swing.JTextField();
        checkSignUpLabel = new javax.swing.JLabel();
        icon8SignUpLabel1 = new javax.swing.JLabel();
        panelLogo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelClient = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelLogIn.setBackground(new java.awt.Color(255, 255, 255));
        panelLogIn.setPreferredSize(new java.awt.Dimension(640, 720));

        signUpLabel.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        signUpLabel.setForeground(new java.awt.Color(204, 204, 204));
        signUpLabel.setText("      Sign up");
        signUpLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signUpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpLabelMouseClicked(evt);
            }
        });

        logInLabel.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        logInLabel.setForeground(new java.awt.Color(45, 142, 151));
        logInLabel.setText("       Login");
        logInLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logInLabel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                logInLabelFocusGained(evt);
            }
        });
        logInLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logInLabelMouseClicked(evt);
            }
        });
        logInLabel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                logInLabelComponentHidden(evt);
            }
        });

        logInSeparator.setBackground(new java.awt.Color(45, 142, 151));
        logInSeparator.setForeground(new java.awt.Color(45, 142, 151));

        signUpSeparator.setBackground(new java.awt.Color(204, 204, 204));
        signUpSeparator.setForeground(new java.awt.Color(204, 204, 204));

        logInPanel.setBackground(new java.awt.Color(255, 255, 255));

        passwordLogInField.setBackground(new java.awt.Color(255, 255, 255));
        passwordLogInField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        passwordLogInField.setForeground(new java.awt.Color(204, 204, 204));
        passwordLogInField.setText("Password");
        passwordLogInField.setBorder(null);
        passwordLogInField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordLogInFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordLogInFieldFocusLost(evt);
            }
        });
        passwordLogInField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordLogInFieldActionPerformed(evt);
            }
        });

        icon2LogInLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_lock_30px.png"))); // NOI18N

        usernameLogInSeparator.setBackground(new java.awt.Color(45, 142, 151));
        usernameLogInSeparator.setForeground(new java.awt.Color(45, 142, 151));

        passwordLogInSeparator.setBackground(new java.awt.Color(45, 142, 151));
        passwordLogInSeparator.setForeground(new java.awt.Color(45, 142, 151));

        usernameLogInField.setBackground(new java.awt.Color(255, 255, 255));
        usernameLogInField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        usernameLogInField.setForeground(new java.awt.Color(204, 204, 204));
        usernameLogInField.setText("Username");
        usernameLogInField.setBorder(null);
        usernameLogInField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameLogInFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameLogInFieldFocusLost(evt);
            }
        });
        usernameLogInField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameLogInFieldActionPerformed(evt);
            }
        });
        usernameLogInField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                usernameLogInFieldPropertyChange(evt);
            }
        });

        icon1LogInLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_customer_30px_3.png"))); // NOI18N

        icon4LogInLabel.setPreferredSize(new java.awt.Dimension(30, 30));

        icon3LogInLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_0_degrees_30px.png"))); // NOI18N

        checkLogInLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_login_50px.png"))); // NOI18N
        checkLogInLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkLogInLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkLogInLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout logInPanelLayout = new javax.swing.GroupLayout(logInPanel);
        logInPanel.setLayout(logInPanelLayout);
        logInPanelLayout.setHorizontalGroup(
            logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkLogInLabel)
                    .addGroup(logInPanelLayout.createSequentialGroup()
                        .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(icon1LogInLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(icon2LogInLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordLogInSeparator)
                            .addComponent(usernameLogInSeparator)
                            .addComponent(usernameLogInField, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordLogInField, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon4LogInLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icon3LogInLabel))
                .addContainerGap())
        );
        logInPanelLayout.setVerticalGroup(
            logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(logInPanelLayout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(icon1LogInLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(usernameLogInField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(icon3LogInLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameLogInSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logInPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordLogInField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(icon2LogInLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(logInPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(icon4LogInLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(passwordLogInSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(checkLogInLabel)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        passwordSignUpField.setBackground(new java.awt.Color(255, 255, 255));
        passwordSignUpField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        passwordSignUpField.setForeground(new java.awt.Color(204, 204, 204));
        passwordSignUpField.setText("Password");
        passwordSignUpField.setBorder(null);
        passwordSignUpField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordSignUpFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordSignUpFieldFocusLost(evt);
            }
        });

        icon2SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_lock_30px.png"))); // NOI18N

        usenameSignUpSeparator.setBackground(new java.awt.Color(45, 142, 151));
        usenameSignUpSeparator.setForeground(new java.awt.Color(45, 142, 151));

        passwordSignUpSeparator.setBackground(new java.awt.Color(45, 142, 151));
        passwordSignUpSeparator.setForeground(new java.awt.Color(45, 142, 151));

        usernameSignUpField.setBackground(new java.awt.Color(255, 255, 255));
        usernameSignUpField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        usernameSignUpField.setForeground(new java.awt.Color(204, 204, 204));
        usernameSignUpField.setText("Username");
        usernameSignUpField.setBorder(null);
        usernameSignUpField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameSignUpFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameSignUpFieldFocusLost(evt);
            }
        });
        usernameSignUpField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameSignUpFieldActionPerformed(evt);
            }
        });
        usernameSignUpField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                usernameSignUpFieldPropertyChange(evt);
            }
        });

        icon1SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_customer_30px_3.png"))); // NOI18N

        icon8SignUpLabel.setPreferredSize(new java.awt.Dimension(30, 30));

        icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_0_degrees_30px.png"))); // NOI18N

        icon3SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_identification_documents_30px_1.png"))); // NOI18N

        firstNameSignUpField.setBackground(new java.awt.Color(255, 255, 255));
        firstNameSignUpField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        firstNameSignUpField.setForeground(new java.awt.Color(204, 204, 204));
        firstNameSignUpField.setText("First Name");
        firstNameSignUpField.setBorder(null);
        firstNameSignUpField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstNameSignUpFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstNameSignUpFieldFocusLost(evt);
            }
        });
        firstNameSignUpField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameSignUpFieldActionPerformed(evt);
            }
        });
        firstNameSignUpField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                firstNameSignUpFieldPropertyChange(evt);
            }
        });

        nameSignUpSeparator.setBackground(new java.awt.Color(45, 142, 151));
        nameSignUpSeparator.setForeground(new java.awt.Color(45, 142, 151));

        lastNameSignUpField.setBackground(new java.awt.Color(255, 255, 255));
        lastNameSignUpField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lastNameSignUpField.setForeground(new java.awt.Color(204, 204, 204));
        lastNameSignUpField.setText("Last Name");
        lastNameSignUpField.setBorder(null);
        lastNameSignUpField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastNameSignUpFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastNameSignUpFieldFocusLost(evt);
            }
        });
        lastNameSignUpField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameSignUpFieldActionPerformed(evt);
            }
        });
        lastNameSignUpField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lastNameSignUpFieldPropertyChange(evt);
            }
        });

        icon4SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_email_30px.png"))); // NOI18N

        eMailSignUpSeparator.setBackground(new java.awt.Color(45, 142, 151));
        eMailSignUpSeparator.setForeground(new java.awt.Color(45, 142, 151));

        eMailSignUpField.setBackground(new java.awt.Color(255, 255, 255));
        eMailSignUpField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        eMailSignUpField.setForeground(new java.awt.Color(204, 204, 204));
        eMailSignUpField.setText("e-Mail");
        eMailSignUpField.setBorder(null);
        eMailSignUpField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                eMailSignUpFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                eMailSignUpFieldFocusLost(evt);
            }
        });
        eMailSignUpField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eMailSignUpFieldActionPerformed(evt);
            }
        });
        eMailSignUpField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                eMailSignUpFieldPropertyChange(evt);
            }
        });

        icon5SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_job_30px.png"))); // NOI18N

        occupationSignUpSeparator.setBackground(new java.awt.Color(45, 142, 151));
        occupationSignUpSeparator.setForeground(new java.awt.Color(45, 142, 151));

        clientSignUpLabel.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        clientSignUpLabel.setForeground(new java.awt.Color(204, 204, 204));
        clientSignUpLabel.setText("Client");
        clientSignUpLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clientSignUpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientSignUpLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clientSignUpLabelMouseExited(evt);
            }
        });

        employeeSignUpLabel.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        employeeSignUpLabel.setForeground(new java.awt.Color(204, 204, 204));
        employeeSignUpLabel.setText(" Emplyee");
        employeeSignUpLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        employeeSignUpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeSignUpLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                employeeSignUpLabelMouseExited(evt);
            }
        });

        adminSignUpLabel.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        adminSignUpLabel.setForeground(new java.awt.Color(204, 204, 204));
        adminSignUpLabel.setText("Admin");
        adminSignUpLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminSignUpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminSignUpLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminSignUpLabelMouseExited(evt);
            }
        });

        cnpSignUpField.setBackground(new java.awt.Color(255, 255, 255));
        cnpSignUpField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cnpSignUpField.setForeground(new java.awt.Color(204, 204, 204));
        cnpSignUpField.setText("CNP");
        cnpSignUpField.setBorder(null);
        cnpSignUpField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cnpSignUpFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cnpSignUpFieldFocusLost(evt);
            }
        });
        cnpSignUpField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnpSignUpFieldActionPerformed(evt);
            }
        });
        cnpSignUpField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cnpSignUpFieldPropertyChange(evt);
            }
        });

        icon6SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_key_30px.png"))); // NOI18N

        numbersSignUpSeparator.setBackground(new java.awt.Color(45, 142, 151));
        numbersSignUpSeparator.setForeground(new java.awt.Color(45, 142, 151));

        phoneSignUpField.setBackground(new java.awt.Color(255, 255, 255));
        phoneSignUpField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        phoneSignUpField.setForeground(new java.awt.Color(204, 204, 204));
        phoneSignUpField.setText("Phone");
        phoneSignUpField.setBorder(null);
        phoneSignUpField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneSignUpFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneSignUpFieldFocusLost(evt);
            }
        });
        phoneSignUpField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneSignUpFieldActionPerformed(evt);
            }
        });
        phoneSignUpField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                phoneSignUpFieldPropertyChange(evt);
            }
        });

        checkSignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_login_50px.png"))); // NOI18N
        checkSignUpLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkSignUpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkSignUpLabelMouseClicked(evt);
            }
        });

        icon8SignUpLabel1.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(icon3SignUpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameSignUpSeparator)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(firstNameSignUpField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lastNameSignUpField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(icon1SignUpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(icon2SignUpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(passwordSignUpSeparator)
                                    .addComponent(usenameSignUpSeparator)
                                    .addComponent(usernameSignUpField, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordSignUpField, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(icon8SignUpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(icon7SignUpLabel)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(icon4SignUpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eMailSignUpSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eMailSignUpField, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(icon5SignUpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(clientSignUpLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(employeeSignUpLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(adminSignUpLabel))
                                    .addComponent(occupationSignUpSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(icon6SignUpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(numbersSignUpSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(cnpSignUpField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(phoneSignUpField))))
                            .addComponent(checkSignUpLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(308, Short.MAX_VALUE)
                    .addComponent(icon8SignUpLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(icon1SignUpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(usernameSignUpField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(icon7SignUpLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usenameSignUpSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordSignUpField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(icon2SignUpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(icon8SignUpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(passwordSignUpSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(icon3SignUpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(firstNameSignUpField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lastNameSignUpField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameSignUpSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(icon4SignUpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eMailSignUpField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eMailSignUpSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(icon5SignUpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clientSignUpLabel)
                        .addComponent(adminSignUpLabel)
                        .addComponent(employeeSignUpLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(occupationSignUpSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon6SignUpLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(phoneSignUpField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cnpSignUpField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numbersSignUpSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkSignUpLabel)
                .addGap(12, 12, 12))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(95, 95, 95)
                    .addComponent(icon8SignUpLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(349, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panelLogInLayout = new javax.swing.GroupLayout(panelLogIn);
        panelLogIn.setLayout(panelLogInLayout);
        panelLogInLayout.setHorizontalGroup(
            panelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogInLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(panelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panelLogInLayout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addComponent(logInSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(signUpSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelLogInLayout.createSequentialGroup()
                            .addComponent(logInLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(signUpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(logInPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(188, Short.MAX_VALUE))
            .addGroup(panelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLogInLayout.createSequentialGroup()
                    .addContainerGap(98, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(188, Short.MAX_VALUE)))
        );
        panelLogInLayout.setVerticalGroup(
            panelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogInLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(panelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(signUpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logInLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logInSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signUpSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(logInPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLogInLayout.createSequentialGroup()
                    .addContainerGap(240, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        panelLogo.setBackground(new java.awt.Color(118, 209, 194));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_cancel_30px.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelLogoLayout = new javax.swing.GroupLayout(panelLogo);
        panelLogo.setLayout(panelLogoLayout);
        panelLogoLayout.setHorizontalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLogoLayout.createSequentialGroup()
                .addContainerGap(604, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        panelLogoLayout.setVerticalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelClient.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_cancel_30px.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_back_to_30px.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_male_user_30px_1.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_search_30px_1.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setText("Search");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(118, 209, 194));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jTable2.setBackground(new java.awt.Color(255, 255, 255));
        jTable2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTable2.setForeground(new java.awt.Color(102, 102, 102));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ggfg", "fgd", "dfgd", null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setFocusable(false);
        jTable2.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable2.setRowHeight(30);
        jTable2.setSelectionBackground(new java.awt.Color(45, 142, 151));
        jScrollPane1.setViewportView(jTable2);
        jTable2.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 20));
        jTable2.getTableHeader().setOpaque(false);
        jTable2.getTableHeader().setBackground(new Color(45,142,151));
        jTable2.getTableHeader().setForeground(new Color(20,20,20));
        jTable2.getTableHeader().setFocusable(false);
        jTable2.getTableHeader().setPreferredSize(new Dimension(jTable2.getWidth(),40));         // set size to header of tabel
        jTable2.getTableHeader().setBackground(Color.BLACK);

        javax.swing.GroupLayout panelClientLayout = new javax.swing.GroupLayout(panelClient);
        panelClient.setLayout(panelClientLayout);
        panelClientLayout.setHorizontalGroup(
            panelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClientLayout.createSequentialGroup()
                .addGap(0, 739, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(panelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClientLayout.createSequentialGroup()
                    .addContainerGap(128, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(122, Short.MAX_VALUE)))
        );
        panelClientLayout.setVerticalGroup(
            panelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addGap(0, 684, Short.MAX_VALUE))
            .addGroup(panelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelClientLayout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 680, Short.MAX_VALUE)))
            .addGroup(panelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClientLayout.createSequentialGroup()
                    .addContainerGap(123, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(83, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logInLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logInLabelMouseClicked
        // TODO add your handling code here:
        logInLabel.setForeground(new Color(45, 142, 151));      
        logInSeparator.setBackground(new java.awt.Color(45, 142, 151));
        logInSeparator.setForeground(new java.awt.Color(45, 142, 151));
        signUpLabel.setForeground(new Color(204, 204, 204));      
        signUpSeparator.setBackground(new java.awt.Color(204, 204, 204));
        signUpSeparator.setForeground(new java.awt.Color(204, 204, 204)); 
        
        jPanel2.setVisible(false);
        logInPanel.setVisible(true);
//        
//       
    }//GEN-LAST:event_logInLabelMouseClicked

    private void signUpLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpLabelMouseClicked
        // TODO add your handling code here:
        logInLabel.setForeground(new Color(204, 204, 204));      
        logInSeparator.setBackground(new java.awt.Color(204, 204, 204));
        logInSeparator.setForeground(new java.awt.Color(204, 204, 204));
        signUpLabel.setForeground(new Color(45, 142, 151));      
        signUpSeparator.setBackground(new java.awt.Color(45, 142, 151));
        signUpSeparator.setForeground(new java.awt.Color(45, 142, 151)); 
        
        jPanel2.setVisible(true);
        logInPanel.setVisible(false);
//       
        cnpSignUpField.setVisible(false);
        phoneSignUpField.setVisible(false);
        numbersSignUpSeparator.setVisible(false);
        icon6SignUpLabel.setVisible(false);
    }//GEN-LAST:event_signUpLabelMouseClicked

    private void usernameLogInFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameLogInFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameLogInFieldActionPerformed

    private void usernameLogInFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameLogInFieldFocusGained
        // TODO add your handling code here:
        if (usernameLogInField.getText().equals("Username"))
        {
            usernameLogInField.setText("");
            icon3LogInLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_0_degrees_30px.png")));
        }
        else if (usernameLogInField.getText().equals("paul"))
        {
            icon3LogInLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_checkmark_30px.png"))); // NOI18N
            icon3LogInLabel.setVisible(true);
        }
        else
        {
            icon3LogInLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_multiply_30px.png"))); // NOI18N
            icon3LogInLabel.setVisible(true);
        }
    }//GEN-LAST:event_usernameLogInFieldFocusGained

    private void usernameLogInFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameLogInFieldFocusLost
        // TODO add your handling code here:
        if (usernameLogInField.getText().equals(""))
        {
            usernameLogInField.setText("Username");
            icon3LogInLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_0_degrees_30px.png")));
        }
        else if (usernameLogInField.getText().equals("paul"))
        {
            icon3LogInLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_checkmark_30px.png"))); // NOI18N
            icon3LogInLabel.setVisible(true);
        }
        else
        {
            icon3LogInLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_multiply_30px.png"))); // NOI18N
            icon3LogInLabel.setVisible(true);
        }
    }//GEN-LAST:event_usernameLogInFieldFocusLost

    private void passwordLogInFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordLogInFieldFocusGained
        // TODO add your handling code here:
        if (String.valueOf(passwordLogInField.getPassword()).equals("Password"))
        {
            passwordLogInField.setText("");
            icon4LogInLabel.setVisible(false);
        }
        else if (String.valueOf(passwordLogInField.getPassword()).equals("12345"))
        {
            icon4LogInLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_checkmark_30px.png"))); // NOI18N
            icon4LogInLabel.setVisible(true);
        }
        else
        {
            icon4LogInLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_multiply_30px.png"))); // NOI18N
            icon4LogInLabel.setVisible(true);
        }

            
    }//GEN-LAST:event_passwordLogInFieldFocusGained

    private void passwordLogInFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordLogInFieldFocusLost
        // TODO add your handling code here:
        if (String.valueOf(passwordLogInField.getPassword()).equals(""))
        {
            passwordLogInField.setText("Password");
            icon4LogInLabel.setVisible(false);
        }
        else if (String.valueOf(passwordLogInField.getPassword()).equals("12345"))
        {
            icon4LogInLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_checkmark_30px.png"))); // NOI18N
            icon4LogInLabel.setVisible(true);
        }
        else
        {
            icon4LogInLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_multiply_30px.png"))); // NOI18N
            icon4LogInLabel.setVisible(true);
        }
    }//GEN-LAST:event_passwordLogInFieldFocusLost

    private void usernameLogInFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_usernameLogInFieldPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameLogInFieldPropertyChange

    private void checkLogInLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkLogInLabelMouseClicked
        // TODO add your handling code here:
//        if(usernameLogInField.getText().indexOf("admin") == 0) {
//            for(ObjectClass admin : this.serviceAdmin.show()) {
//                if(((Admin)admin).getUsername().equals(usernameLogInField.getText())&&((Admin)admin).getPassword().equals(String.valueOf(passwordLogInField.getPassword())));
//                System.exit(0);
//            }
//        }
//        else
//            if(usernameLogInField.getText().indexOf("client") == 0) {
//                
//            }
//            else
//                if(usernameLogInField.getText().indexOf("employee") == 0) {
//                    
//                }
//                else {
//                    
//                }
        panelClient.setVisible(true);
        panelLogIn.setVisible(false);
        panelLogo.setVisible(false);
    }//GEN-LAST:event_checkLogInLabelMouseClicked

    private void logInLabelComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_logInLabelComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_logInLabelComponentHidden

    private void logInLabelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_logInLabelFocusGained
        // TODO add your handling code here:
        Color color = new Color(45,142,151);
        if(logInLabel.getBackground()==color)
            logInLabel.setBackground(Color.RED);
    }//GEN-LAST:event_logInLabelFocusGained

    private void passwordSignUpFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordSignUpFieldFocusGained
        // TODO add your handling code here:
        if (String.valueOf(passwordSignUpField.getPassword()).equals("Password"))
        {
            passwordSignUpField.setText("");
            icon8SignUpLabel.setVisible(false);
        }
        else if (String.valueOf(passwordSignUpField.getPassword()).equals("12345"))
        {
            icon8SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_checkmark_30px.png"))); // NOI18N
            icon8SignUpLabel.setVisible(true);
        }
        else
        {
            icon8SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_multiply_30px.png"))); // NOI18N
            icon8SignUpLabel.setVisible(true);
        }
    }//GEN-LAST:event_passwordSignUpFieldFocusGained

    private void passwordSignUpFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordSignUpFieldFocusLost
        // TODO add your handling code here:
        if (String.valueOf(passwordSignUpField.getPassword()).equals(""))
        {
            passwordSignUpField.setText("Password");
            icon8SignUpLabel.setVisible(false);
        }
        else if (String.valueOf(passwordSignUpField.getPassword()).equals("12345"))
        {
            icon8SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_checkmark_30px.png"))); // NOI18N
            icon8SignUpLabel.setVisible(true);
        }
        else
        {
            icon8SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_multiply_30px.png"))); // NOI18N
            icon8SignUpLabel.setVisible(true);
        }
    }//GEN-LAST:event_passwordSignUpFieldFocusLost

    private void usernameSignUpFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameSignUpFieldFocusGained
        // TODO add your handling code here:
        if (usernameSignUpField.getText().equals("Username"))
        {
            usernameSignUpField.setText("");
            icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_0_degrees_30px.png")));
        }
        else if (usernameSignUpField.getText().equals("paul"))
        {
            icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_checkmark_30px.png"))); // NOI18N
            icon7SignUpLabel.setVisible(true);
        }
        else
        {
            icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_multiply_30px.png"))); // NOI18N
            icon7SignUpLabel.setVisible(true);
        }
    }//GEN-LAST:event_usernameSignUpFieldFocusGained

    private void usernameSignUpFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameSignUpFieldFocusLost
        // TODO add your handling code here:
        if (usernameSignUpField.getText().equals(""))
        {
            usernameSignUpField.setText("Username");
            icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_0_degrees_30px.png")));
        }
        else if (usernameSignUpField.getText().equals("paul"))
        {
            icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_checkmark_30px.png"))); // NOI18N
            icon7SignUpLabel.setVisible(true);
        }
        else
        {
            icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_multiply_30px.png"))); // NOI18N
            icon7SignUpLabel.setVisible(true);
        }
    }//GEN-LAST:event_usernameSignUpFieldFocusLost

    private void usernameSignUpFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameSignUpFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameSignUpFieldActionPerformed

    private void usernameSignUpFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_usernameSignUpFieldPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameSignUpFieldPropertyChange

    private void firstNameSignUpFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameSignUpFieldFocusGained
        // TODO add your handling code here:
        if (firstNameSignUpField.getText().equals("First Name"))
        {
            firstNameSignUpField.setText("");
            //icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_0_degrees_30px.png")));
        }
        else if (firstNameSignUpField.getText().equals("paul"))
        {
            //icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_checkmark_30px.png"))); // NOI18N
            //icon7SignUpLabel.setVisible(true);
        }
        else
        {
            //icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_multiply_30px.png"))); // NOI18N
            //icon7SignUpLabel.setVisible(true);
        }
    }//GEN-LAST:event_firstNameSignUpFieldFocusGained

    private void firstNameSignUpFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameSignUpFieldFocusLost
        // TODO add your handling code here:
        if (firstNameSignUpField.getText().equals(""))
        {
            firstNameSignUpField.setText("First Name");
            //icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_0_degrees_30px.png")));
        }
        else if (usernameSignUpField.getText().equals("paul"))
        {
            //icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_checkmark_30px.png"))); // NOI18N
            //icon7SignUpLabel.setVisible(true);
        }
        else
        {
            //icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_multiply_30px.png"))); // NOI18N
            //icon7SignUpLabel.setVisible(true);
        }
    }//GEN-LAST:event_firstNameSignUpFieldFocusLost

    private void firstNameSignUpFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameSignUpFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameSignUpFieldActionPerformed

    private void firstNameSignUpFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_firstNameSignUpFieldPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameSignUpFieldPropertyChange

    private void lastNameSignUpFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameSignUpFieldFocusGained
        // TODO add your handling code here:
        if (lastNameSignUpField.getText().equals("Last Name"))
        {
            lastNameSignUpField.setText("");
            //icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_0_degrees_30px.png")));
        }
        else if (firstNameSignUpField.getText().equals("paul"))
        {
            //icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_checkmark_30px.png"))); // NOI18N
            //icon7SignUpLabel.setVisible(true);
        }
        else
        {
            //icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_multiply_30px.png"))); // NOI18N
            //icon7SignUpLabel.setVisible(true);
        }
    }//GEN-LAST:event_lastNameSignUpFieldFocusGained

    private void lastNameSignUpFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameSignUpFieldFocusLost
        // TODO add your handling code here:
        if (lastNameSignUpField.getText().equals(""))
        {
            lastNameSignUpField.setText("Last Name");
            //icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_0_degrees_30px.png")));
        }
        else if (usernameSignUpField.getText().equals("paul"))
        {
            //icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_checkmark_30px.png"))); // NOI18N
            //icon7SignUpLabel.setVisible(true);
        }
        else
        {
            //icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_multiply_30px.png"))); // NOI18N
            //icon7SignUpLabel.setVisible(true);
        }
    }//GEN-LAST:event_lastNameSignUpFieldFocusLost

    private void lastNameSignUpFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameSignUpFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameSignUpFieldActionPerformed

    private void lastNameSignUpFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lastNameSignUpFieldPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameSignUpFieldPropertyChange

    private void eMailSignUpFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_eMailSignUpFieldFocusGained
        // TODO add your handling code here:
        if (eMailSignUpField.getText().equals("e-Mail"))
        {
            eMailSignUpField.setText("");
            //icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_0_degrees_30px.png")));
        }
        else if (firstNameSignUpField.getText().equals("paul"))
        {
            //icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_checkmark_30px.png"))); // NOI18N
            //icon7SignUpLabel.setVisible(true);
        }
        else
        {
            //icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_multiply_30px.png"))); // NOI18N
            //icon7SignUpLabel.setVisible(true);
        }
    }//GEN-LAST:event_eMailSignUpFieldFocusGained

    private void eMailSignUpFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_eMailSignUpFieldFocusLost
        // TODO add your handling code here:
        if (eMailSignUpField.getText().equals(""))
        {
            eMailSignUpField.setText("e-Mail");
            //icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_0_degrees_30px.png")));
        }
        else if (usernameSignUpField.getText().equals("paul"))
        {
            //icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_checkmark_30px.png"))); // NOI18N
            //icon7SignUpLabel.setVisible(true);
        }
        else
        {
            //icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_multiply_30px.png"))); // NOI18N
            //icon7SignUpLabel.setVisible(true);
        }
    }//GEN-LAST:event_eMailSignUpFieldFocusLost

    private void eMailSignUpFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eMailSignUpFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eMailSignUpFieldActionPerformed

    private void eMailSignUpFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_eMailSignUpFieldPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_eMailSignUpFieldPropertyChange

    private void cnpSignUpFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnpSignUpFieldFocusGained
        // TODO add your handling code here:
        if (cnpSignUpField.getText().equals("CNP") || cnpSignUpField.getText().equals("Security Code"))
        {
            cnpSignUpField.setText("");
            //icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_0_degrees_30px.png")));
        }
        else if (firstNameSignUpField.getText().equals("paul"))
        {
            //icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_checkmark_30px.png"))); // NOI18N
            //icon7SignUpLabel.setVisible(true);
        }
        else
        {
            //icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_multiply_30px.png"))); // NOI18N
            //icon7SignUpLabel.setVisible(true);
        }
    }//GEN-LAST:event_cnpSignUpFieldFocusGained

    private void cnpSignUpFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnpSignUpFieldFocusLost
        // TODO add your handling code here:
        if (cnpSignUpField.getText().equals(""))
        {
            if(employeeSignUpLabel.getForeground().equals(new Color(45,142,151)))
                cnpSignUpField.setText("CNP");
            if(adminSignUpLabel.getForeground().equals(new Color(45,142,151)))
                cnpSignUpField.setText("Security Code");
            //icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_0_degrees_30px.png")));
        }
        else if (usernameSignUpField.getText().equals("paul"))
        {
            //icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_checkmark_30px.png"))); // NOI18N
            //icon7SignUpLabel.setVisible(true);
        }
        else
        {
            //icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_multiply_30px.png"))); // NOI18N
            //icon7SignUpLabel.setVisible(true);
        }
    }//GEN-LAST:event_cnpSignUpFieldFocusLost

    private void cnpSignUpFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnpSignUpFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnpSignUpFieldActionPerformed

    private void cnpSignUpFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cnpSignUpFieldPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cnpSignUpFieldPropertyChange

    private void phoneSignUpFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneSignUpFieldFocusGained
        // TODO add your handling code here:
        if (phoneSignUpField.getText().equals("Phone"))
        {
            phoneSignUpField.setText("");
            //icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_0_degrees_30px.png")));
        }
        else if (firstNameSignUpField.getText().equals("paul"))
        {
            //icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_checkmark_30px.png"))); // NOI18N
            //icon7SignUpLabel.setVisible(true);
        }
        else
        {
            //icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_multiply_30px.png"))); // NOI18N
            //icon7SignUpLabel.setVisible(true);
        }
    }//GEN-LAST:event_phoneSignUpFieldFocusGained

    private void phoneSignUpFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneSignUpFieldFocusLost
        // TODO add your handling code here:
        if (phoneSignUpField.getText().equals(""))
        {
            phoneSignUpField.setText("Phone");
            //icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_0_degrees_30px.png")));
        }
        else if (usernameSignUpField.getText().equals("paul"))
        {
            //icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_checkmark_30px.png"))); // NOI18N
            //icon7SignUpLabel.setVisible(true);
        }
        else
        {
            //icon7SignUpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/icons8_multiply_30px.png"))); // NOI18N
            //icon7SignUpLabel.setVisible(true);
        }
    }//GEN-LAST:event_phoneSignUpFieldFocusLost

    private void phoneSignUpFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneSignUpFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneSignUpFieldActionPerformed

    private void phoneSignUpFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_phoneSignUpFieldPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneSignUpFieldPropertyChange

    private void checkSignUpLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkSignUpLabelMouseClicked
        // TODO add your handling code here:
        panelClient.setVisible(true);
        panelLogIn.setVisible(false);
        panelLogo.setVisible(false);
    }//GEN-LAST:event_checkSignUpLabelMouseClicked

    private void clientSignUpLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientSignUpLabelMouseClicked
        // TODO add your handling code here:
        clientSignUpLabel.setForeground(new Color(45,142,151));
        employeeSignUpLabel.setForeground(new Color(204,204,204));
        adminSignUpLabel.setForeground(new Color(204,204,204));
        
        cnpSignUpField.setVisible(false);
        phoneSignUpField.setVisible(false);
        numbersSignUpSeparator.setVisible(false);
        icon6SignUpLabel.setVisible(false);

    }//GEN-LAST:event_clientSignUpLabelMouseClicked

    private void clientSignUpLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientSignUpLabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_clientSignUpLabelMouseExited

    private void employeeSignUpLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeSignUpLabelMouseClicked
        // TODO add your handling code here:
        employeeSignUpLabel.setForeground(new Color(45,142,151));
        clientSignUpLabel.setForeground(new Color(204,204,204));
        adminSignUpLabel.setForeground(new Color(204,204,204));
        
        cnpSignUpField.setVisible(true);
        phoneSignUpField.setVisible(true);
        numbersSignUpSeparator.setVisible(true);
        icon6SignUpLabel.setVisible(true);
        
        cnpSignUpField.setText("CNP");
        phoneSignUpField.setText("Phone");
    }//GEN-LAST:event_employeeSignUpLabelMouseClicked

    private void employeeSignUpLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeSignUpLabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeSignUpLabelMouseExited

    private void adminSignUpLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminSignUpLabelMouseClicked
        // TODO add your handling code here:
        adminSignUpLabel.setForeground(new Color(45,142,151));
        clientSignUpLabel.setForeground(new Color(204,204,204));
        employeeSignUpLabel.setForeground(new Color(204,204,204));
        
        cnpSignUpField.setVisible(true);
        phoneSignUpField.setVisible(true);
        numbersSignUpSeparator.setVisible(true);
        icon6SignUpLabel.setVisible(true);
        
        cnpSignUpField.setText("Security Code");
        phoneSignUpField.setText("Phone");
    }//GEN-LAST:event_adminSignUpLabelMouseClicked

    private void adminSignUpLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminSignUpLabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_adminSignUpLabelMouseExited

    private void passwordLogInFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordLogInFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordLogInFieldActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        panelClient.setVisible(false);
        panelLogIn.setVisible(true);
        panelLogo.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    //    public static void main(String args[]) throws ClassNotFoundException, UnsupportedLookAndFeelException {

    public static void main(String args[]) throws ClassNotFoundException {

//        try {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

//            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
//            UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
//            
            
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Login(serviceAdmin,serviceClient,serviceEmployee).setVisible(true);
                }
            });
//        } catch (InstantiationException ex) {
//            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
//        }
        //</editor-fold>
    }

    private static Service serviceAdmin;
    private static Service serviceClient;
    private static Service serviceEmployee;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminSignUpLabel;
    private javax.swing.JLabel checkLogInLabel;
    private javax.swing.JLabel checkSignUpLabel;
    private javax.swing.JLabel clientSignUpLabel;
    private javax.swing.JTextField cnpSignUpField;
    private javax.swing.JTextField eMailSignUpField;
    private javax.swing.JSeparator eMailSignUpSeparator;
    private javax.swing.JLabel employeeSignUpLabel;
    private javax.swing.JTextField firstNameSignUpField;
    private javax.swing.JLabel icon1LogInLabel;
    private javax.swing.JLabel icon1SignUpLabel;
    private javax.swing.JLabel icon2LogInLabel;
    private javax.swing.JLabel icon2SignUpLabel;
    private javax.swing.JLabel icon3LogInLabel;
    private javax.swing.JLabel icon3SignUpLabel;
    private javax.swing.JLabel icon4LogInLabel;
    private javax.swing.JLabel icon4SignUpLabel;
    private javax.swing.JLabel icon5SignUpLabel;
    private javax.swing.JLabel icon6SignUpLabel;
    private javax.swing.JLabel icon7SignUpLabel;
    private javax.swing.JLabel icon8SignUpLabel;
    private javax.swing.JLabel icon8SignUpLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField lastNameSignUpField;
    private javax.swing.JLabel logInLabel;
    private javax.swing.JPanel logInPanel;
    private javax.swing.JSeparator logInSeparator;
    private javax.swing.JSeparator nameSignUpSeparator;
    private javax.swing.JSeparator numbersSignUpSeparator;
    private javax.swing.JSeparator occupationSignUpSeparator;
    private javax.swing.JPanel panelClient;
    private javax.swing.JPanel panelLogIn;
    private javax.swing.JPanel panelLogo;
    private javax.swing.JPasswordField passwordLogInField;
    private javax.swing.JSeparator passwordLogInSeparator;
    private javax.swing.JPasswordField passwordSignUpField;
    private javax.swing.JSeparator passwordSignUpSeparator;
    private javax.swing.JTextField phoneSignUpField;
    private javax.swing.JLabel signUpLabel;
    private javax.swing.JSeparator signUpSeparator;
    private javax.swing.JSeparator usenameSignUpSeparator;
    private javax.swing.JTextField usernameLogInField;
    private javax.swing.JSeparator usernameLogInSeparator;
    private javax.swing.JTextField usernameSignUpField;
    // End of variables declaration//GEN-END:variables
}
